name: linting, testing and building
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [17.x]
        
    steps:
      - uses: action/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }} ğŸš€
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies ğŸ“¦
        run: npm install
      - name: Build for prod ğŸ—ï¸
        run: npm run build:prod
      - name: Linting ğŸ§¹
        run: npm run lint:ts
      - name: Linting scss ğŸ§¹
        run: npm run lint:scss
       - name: Testing ğŸ§ª
        run: npm run unit 
